services:
    cleantalk.antispam.listener:
        class: cleantalk\antispam\event\main_listener
        arguments:
            - @template
            - @config
            - @user
            - @request
            - @dbal.conn
        tags:
            - { name: event.listener }
    cleantalk.antispam.cron.task.cleantalk_antispam_sfw_logs_send:
        class: cleantalk\antispam\cron\task\cleantalk_antispam_sfw_logs_send
        arguments:
            - @config
        calls:
            - [set_name, [cron.task.cleantalk_antispam_sfw_logs_send]]
        tags:
            - { name: cron.task }
    cleantalk.antispam.cron.task.cleantalk_antispam_sfw_update:
        class: cleantalk\antispam\cron\task\cleantalk_antispam_sfw_update
        arguments:
            - @config
        calls:
            - [set_name, [cron.task.cleantalk_antispam_sfw_update]]
        tags:
            - { name: cron.task }