services:
    cleantalk.antispam.listener:
        class: cleantalk\antispam\event\main_listener
        arguments:
            - @controller.helper
            - @template
        tags:
            - { name: event.listener }
